import { GooberRarity } from "../../types";

export default {
  [GooberRarity.COMMON]: {
    backgrounds: [
      "BlueSplat",
      "Grey Action",
      "Orange Dark Splat",
      "Dark Grey Splat",
      "Action Green",
      "Ice Blue action",
      "Green Splat",
      "Purple Dark",
      "Green",
      "Purple Splat",
      "Orange Dark",
      "Green Dark",
      "Mustard Dark",
      "Dark Grey",
      "Mustard",
      "Orange",
      "DarkBlue",
      "Blue",
      "Grey",
      "Purple",
      "RoseRed",
      "Red",
    ],
    accessories: [
      "Cupcake",
      "Cigarette",
      "Gum",
      "Bowtie",
      "Flashlight",
      "Dog Tags",
      "Beard",
      "Bandaids",
      "Surgical Mask",
      "Whistle",
      "Scarf",
      "Stethoscope",
      "Spike Collar",
      "Stickers",
      "Pizza Slice",
      "Lobster Bib",
      "Hamburger",
      "Binky",
      "HotDog",
      "Smile 2",
      "Smile 3",
      "Smile 1",
    ],
    brains: [
      "RubberDucky",
      "Rubics Cube",
      "Hammer",
      "KickMe",
      "Mug",
      "Dead Fish",
      "Old Cell Phone",
      "Milk",
      "Compass",
      "Notepad",
      "Remote Control",
      "Princess Wand",
      "Watch",
      "Rusty Can",
      "Alarm Clock",
      "Old Boot",
      "Camera",
      "Spatula",
      "Tooth Brush",
      "Water Bottle",
    ],
    colors: [
      "Gradient Swamp",
      "Rose Pink",
      "Sky Blue",
      "Peach",
      "Cobalt",
      "Deep Pink",
      "Lavender",
      "Clover",
      "Lemon",
      "Blush",
      "Aqua",
      "Blue",
      "Red",
      "Orange",
      "Green",
      "Purple",
      "Yellow",
      "Base Green",
    ],
    outfits: [
      "Chef Suit",
      "FastFood Appron",
      "Convict Jumper",
      "Leprachaun Outfit",
      "Graduation Gown",
      "Basketball Jersey",
      "Mime",
      "Life Vest",
      "Workout Suit",
      "Winter Coat",
      "Scuba",
      "Pirate Shirt",
      "TankTop",
      "Bra",
      "Hobo",
      "CropTop",
      "Button Up Shirt",
      "Polo Shirt",
    ],
    effects: ["Sparkles", "Butterflies", "Flies", "Bubbles", "Blinking"],
    hats: [
      "Greek Leaves",
      "Explorer",
      "Pimp Hat",
      "Jester Hat",
      "Chef Hat",
      "Bum Beanie",
      "Powdered Wig",
      "SunHat",
      "Scuba Hat",
      "WinterCap",
      "RedCap",
      "FlipBack",
      "FastFood",
      "HeadBand",
      "Pirate",
      "Sombrero",
    ],
  },
  [GooberRarity.RARE]: {
    backgrounds: ["Groovy", "Looney Orange"],
    accessories: [
      "Monocle",
      "Disguise Mask",
      "Bandanna",
      "Aviator Glasses",
      "Diploma",
      "Dom Mask",
      "Clown Nose",
      "Joint",
      "Pearl Necklace",
      "Teeth",
      "Twirl Mustache",
      "Sunglasses",
      "Pipe",
      "Mustache",
      "Coffee Paper Cup",
      "Bottle Message",
      "Cigar",
      "Ear Rings",
      "Wheat Straw",
    ],
    brains: [
      "GasCan",
      "DataPad",
      "Dino Egg",
      "Goober",
      "Human Brain",
      "Golden Apple",
      "Game Controller",
      "Monkey Doll",
      "Gem",
      "LightBulb",
      "Computer Chip",
      "LavaLamp",
      "Goldfish",
      "USB",
      "Wedding Ring",
      "Wallet",
      "Trophy",
    ],
    colors: [
      "Astro Plain",
      "BubbleGum",
      "NightLife",
      "Reef",
      "Clear Sky",
      "Berry",
      "Neon Berry",
      "Sunset 2",
      "Sunset",
    ],
    outfits: [
      "Noble",
      "Astronaut Suit",
      "General Uniform",
      "Bunny",
      "Dom Leather Suit",
      "Pimp Suit",
      "Tuxedo",
      "Tutu",
      "Wizard Robe",
      "Unicorn Onesie",
      "Viking Armor",
      "Princess",
      "Super Hero",
      "Jester",
      "Officer Uniform",
      "Poncho",
      "Explorer",
      "Fishnets",
      "Cupid Toga",
      "Hippie",
      "Jock Jacket",
      "Sailor Suit",
      "Toga",
      "Sundress",
      "Reporter",
    ],
    effects: ["Alien", "Wisps", "Robot Scan"],
    hats: [
      "Bunny Ears",
      "General Hat",
      "Leprechaun Hat",
      "Crown",
      "French Hat",
      "Press Hat",
      "Princess Cap",
      "Graduation Cap",
      "Halo",
      "Dunce Hat",
      "Bowler Hat",
      "PartyCap",
      "hardHat",
      "Hippie Flowers",
      "Officer Cap",
      "Sailor Cap",
      "StreetCone",
      "Viking Helm",
      "Tin Foil",
      "Wizard Hat",
      "Unicorn Hat",
      "Underworld Horns",
    ],
  },
  [GooberRarity.UBER_RARE]: {
    backgrounds: ["Chemico Tunnels", "The Swamps", "GoobShack Storage Room"],
    accessories: ["Gas Mask", "Gold Chain", "Outlander Mask"],
    brains: ["Clu Logo", "Gold Treasure", "Enchanted Book"],
    colors: ["Gold", "Reverse Neon Berry", "Rainbow", "Retro Sunset"],
    outfits: [
      "Clu Jacket",
      "Dragon Armor",
      "SuperStar",
      "Necromancer",
      "King Robe",
      "Bone Shaman",
      "Knight Armor",
      "Space Ranger Uniform",
      "Outlander",
      "End Is Goo",
    ],
    effects: ["Lightning Effect", "Laser Beam Eyes Animation"],
    hats: [
      "Penguin",
      "Whale",
      "Saber Skull",
      "Outlander Mohawk",
      "Necromancer Hood",
      "Rockstar",
      "Space Ranger Visor",
      "Shiba",
      "Bull",
      "Astronaut Helmet",
      "Knight Helmet",
      "Cat",
      "Clu Cap",
      "Monkey",
      "Dragon Horns",
    ],
  },
};
